import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import api from '../../services/api';
import { ENDPOINTS } from '../../constants/api';
import LoadingSpinner from '../../components/common/LoadingSpinner';

const PRIMARY = '#6C63FF';

const ExportCourseDataScreen = ({ route, navigation }) => {
  const { courseId, courseName } = route.params;
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [courseData, setCourseData] = useState(null);

  useEffect(() => {
    fetchCourseData();
  }, []);

  const fetchCourseData = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/data-export/course/${courseId}`);
      setCourseData(response.data.data);
    } catch (err) {
      Alert.alert('Error', err.response?.data?.message || 'Failed to load course data');
    } finally {
      setLoading(false);
    }
  };

  const generatePDFContent = (data) => {
    const date = new Date(data.exportDate).toLocaleDateString();
    
    let content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    h1 { color: #6C63FF; border-bottom: 3px solid #6C63FF; padding-bottom: 10px; }
    h2 { color: #333; margin-top: 30px; border-bottom: 2px solid #ddd; padding-bottom: 5px; }
    .info-box { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 15px 0; }
    .stat { display: inline-block; margin: 10px 20px 10px 0; }
    .stat-label { font-weight: bold; color: #666; }
    .stat-value { font-size: 24px; color: #6C63FF; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { background: #6C63FF; color: white; padding: 10px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #ddd; }
    tr:hover { background: #f9f9f9; }
    .footer { margin-top: 40px; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📊 Course Data Export</h1>
  
  <div class="info-box">
    <p><strong>Course:</strong> ${data.course.title}</p>
    <p><strong>Instructor:</strong> ${data.course.instructor}</p>
    <p><strong>Created:</strong> ${new Date(data.course.createdAt).toLocaleDateString()}</p>
    <p><strong>Export Date:</strong> ${date}</p>
  </div>

  <h2>📈 Statistics</h2>
  <div class="info-box">
    <div class="stat">
      <div class="stat-label">Total Enrollments</div>
      <div class="stat-value">${data.statistics.totalEnrollments}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Average Completion</div>
      <div class="stat-value">${data.statistics.averageCompletion.toFixed(1)}%</div>
    </div>
  </div>

  <h2>👥 Enrolled Students</h2>
  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Email</th>
        <th>Enrolled Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${data.enrollments.map(e => `
        <tr>
          <td>${e.student || 'N/A'}</td>
          <td>${e.email || 'N/A'}</td>
          <td>${new Date(e.enrolledAt).toLocaleDateString()}</td>
          <td>${e.status}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <h2>📊 Student Progress</h2>
  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Completion %</th>
        <th>Completed Lessons</th>
        <th>Last Accessed</th>
      </tr>
    </thead>
    <tbody>
      ${data.progress.map(p => `
        <tr>
          <td>${p.student || 'N/A'}</td>
          <td>${p.completionPercentage}%</td>
          <td>${p.completedLessons}</td>
          <td>${p.lastAccessed ? new Date(p.lastAccessed).toLocaleDateString() : 'Never'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by E-Learning Platform</p>
    <p>${date}</p>
  </div>
</body>
</html>
    `;
    
    return content;
  };

  const exportAsPDF = async () => {
    if (!courseData) {
      Alert.alert('Error', 'No data to export');
      return;
    }

    try {
      setExporting(true);

      // Generate HTML content
      const htmlContent = generatePDFContent(courseData);
      
      // Create filename
      const fileName = `${courseName.replace(/[^a-z0-9]/gi, '_')}_export_${Date.now()}.html`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;

      // Write HTML file
      await FileSystem.writeAsStringAsync(fileUri, htmlContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      // Check if sharing is available
      const isAvailable = await Sharing.isAvailableAsync();
      
      if (isAvailable) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/html',
          dialogTitle: 'Export Course Data',
          UTI: 'public.html',
        });
        
        Alert.alert(
          'Success', 
          'Course data exported! You can open this HTML file in a browser and print/save as PDF.',
          [{ text: 'OK' }]
        );
      } else {
        Alert.alert('Success', `File saved to: ${fileUri}`);
      }
    } catch (err) {
      console.error('Export error:', err);
      Alert.alert('Error', 'Failed to export data: ' + err.message);
    } finally {
      setExporting(false);
    }
  };

  const exportAsJSON = async () => {
    if (!courseData) {
      Alert.alert('Error', 'No data to export');
      return;
    }

    try {
      setExporting(true);

      const fileName = `${courseName.replace(/[^a-z0-9]/gi, '_')}_export_${Date.now()}.json`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;

      await FileSystem.writeAsStringAsync(
        fileUri, 
        JSON.stringify(courseData, null, 2),
        { encoding: FileSystem.EncodingType.UTF8 }
      );

      const isAvailable = await Sharing.isAvailableAsync();
      
      if (isAvailable) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'application/json',
          dialogTitle: 'Export Course Data (JSON)',
        });
        Alert.alert('Success', 'Course data exported as JSON!');
      } else {
        Alert.alert('Success', `File saved to: ${fileUri}`);
      }
    } catch (err) {
      console.error('Export error:', err);
      Alert.alert('Error', 'Failed to export data: ' + err.message);
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return <LoadingSpinner text="Loading course data..." />;
  }

  if (!courseData) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>No data available</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Ionicons name="download-outline" size={48} color={PRIMARY} />
        <Text style={styles.title}>Export Course Data</Text>
        <Text style={styles.subtitle}>{courseName}</Text>
      </View>

      {/* Statistics Preview */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>📊 Data Summary</Text>
        
        <View style={styles.statsGrid}>
          <View style={styles.statCard}>
            <Text style={styles.statValue}>{courseData.statistics.totalEnrollments}</Text>
            <Text style={styles.statLabel}>Total Students</Text>
          </View>
          
          <View style={styles.statCard}>
            <Text style={styles.statValue}>
              {courseData.statistics.averageCompletion.toFixed(1)}%
            </Text>
            <Text style={styles.statLabel}>Avg Completion</Text>
          </View>
        </View>

        <View style={styles.infoBox}>
          <View style={styles.infoRow}>
            <Ionicons name="people-outline" size={20} color="#666" />
            <Text style={styles.infoText}>
              {courseData.enrollments.length} enrolled students
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Ionicons name="bar-chart-outline" size={20} color="#666" />
            <Text style={styles.infoText}>
              {courseData.progress.length} progress records
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Ionicons name="calendar-outline" size={20} color="#666" />
            <Text style={styles.infoText}>
              Exported: {new Date(courseData.exportDate).toLocaleDateString()}
            </Text>
          </View>
        </View>
      </View>

      {/* Export Options */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>📥 Export Options</Text>
        
        <TouchableOpacity
          style={[styles.exportBtn, styles.pdfBtn]}
          onPress={exportAsPDF}
          disabled={exporting}
        >
          <Ionicons name="document-text-outline" size={24} color="#fff" />
          <View style={styles.exportBtnContent}>
            <Text style={styles.exportBtnTitle}>Export as HTML/PDF</Text>
            <Text style={styles.exportBtnDesc}>
              Download HTML file that can be printed as PDF
            </Text>
          </View>
          <Ionicons name="chevron-forward" size={20} color="#fff" />
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.exportBtn, styles.jsonBtn]}
          onPress={exportAsJSON}
          disabled={exporting}
        >
          <Ionicons name="code-outline" size={24} color="#fff" />
          <View style={styles.exportBtnContent}>
            <Text style={styles.exportBtnTitle}>Export as JSON</Text>
            <Text style={styles.exportBtnDesc}>
              Download raw data in JSON format
            </Text>
          </View>
          <Ionicons name="chevron-forward" size={20} color="#fff" />
        </TouchableOpacity>
      </View>

      {/* Instructions */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>ℹ️ Instructions</Text>
        <View style={styles.instructionBox}>
          <Text style={styles.instructionTitle}>How to create PDF:</Text>
          <Text style={styles.instructionText}>
            1. Export as HTML/PDF{'\n'}
            2. Open the downloaded HTML file in a browser{'\n'}
            3. Use browser's Print function (Ctrl+P){'\n'}
            4. Select "Save as PDF" as destination{'\n'}
            5. Save your PDF file
          </Text>
        </View>
      </View>

      {exporting && (
        <View style={styles.loadingOverlay}>
          <LoadingSpinner text="Exporting..." />
        </View>
      )}

      <View style={{ height: 40 }} />
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    backgroundColor: '#fff',
    padding: 24,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginTop: 12,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    marginTop: 4,
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: PRIMARY + '20',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: PRIMARY,
  },
  statLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  infoBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 12,
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  pdfBtn: {
    backgroundColor: '#EF4444',
  },
  jsonBtn: {
    backgroundColor: '#10B981',
  },
  exportBtnContent: {
    flex: 1,
    marginLeft: 12,
  },
  exportBtnTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  exportBtnDesc: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
    marginTop: 2,
  },
  instructionBox: {
    backgroundColor: '#FFF9E6',
    borderLeftWidth: 4,
    borderLeftColor: '#FFB347',
    borderRadius: 8,
    padding: 16,
  },
  instructionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginBottom: 8,
  },
  instructionText: {
    fontSize: 13,
    color: '#666',
    lineHeight: 20,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginTop: 40,
  },
});

export default ExportCourseDataScreen;
